name: Reading notes
description: Weekly reading notes
title: "[reading] Week <N>: Notes"
labels: [reading]
body:
  - type: input
    id: week
    attributes:
      label: Week #
      placeholder: "e.g., 3"
    validations:
      required: true
  - type: textarea
    id: chapters
    attributes:
      label: Chapters covered
  - type: textarea
    id: insights
    attributes:
      label: Key insights
  - type: textarea
    id: questions
    attributes:
      label: Open questions
