name: Move issue card to In Progress on push (branch naming conv.)
on: push
permissions: { contents: read, issues: write, projects: write }
jobs:
  move_card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const branch = context.ref.replace('refs/heads/','');
            const m = branch.match(/issue-(\d+)/i) || branch.match(/i(\d+)/); if (!m) return; const issue_number = parseInt(m[1],10);
            const {owner, repo} = context.repo;
            const projects = await github.rest.projects.listForRepo({owner, repo}); const project = projects.data.find(p=>p.name==='Course Kanban'); if (!project) { core.setFailed('Run Setup Kanban first.'); return; }
            const cols = await github.rest.projects.listColumns({project_id: project.id}); const inprog = cols.data.find(c=>c.name==='In Progress') || cols.data[0];
            for (const col of cols.data) {
              const cards = await github.rest.projects.listCards({column_id: col.id, per_page: 100});
              const card = cards.data.find(cd=>cd.content_url && cd.content_url.endsWith(`/issues/${issue_number}`));
              if (card) { await github.rest.projects.moveCard({card_id: card.id, position:'top', column_id: inprog.id}); return; }
            }
            const issue = (await github.rest.issues.get({owner, repo, issue_number})).data;
            await github.rest.projects.createCard({column_id: inprog.id, content_id: issue.id, content_type:'Issue'});
